version: '3.9'

services:
  api:
    image: '23730/employee-management:employee-management-api'
    build:
      context: .
    container_name: api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ui:
    image: employee-management-ui:latest
    ports:
      - "3000:3000"